import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "@/components/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  // The template puts the brand behind every page's own title, so a bookmarked
  // tab reads "Courses · GoTutors Academy" rather than just "Courses".
  title: { default: "GoTutors Academy", template: "%s · GoTutors Academy" },
  description: "Learning management platform",
  // `src/app/icon.svg` and `src/app/apple-icon.png` are picked up by filename;
  // both are generated by `npm run brand:mark`.
  applicationName: "GoTutors Academy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable} suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
