#!/usr/bin/env node
/**
 * Regenerate `src/lib/brand-mark.ts` from `public/go-wordmark-navy.svg`.
 *
 * The app draws the logo inline rather than through an `<img>`, because the
 * sidebar and the login hero are navy and the mark has to invert — and because
 * `@react-pdf/renderer` cannot load an SVG file at all. Inline means the path
 * data has to exist as strings in TypeScript, and hand-copying 4KB of curves is
 * exactly the kind of transcription nobody can review. So: keep the .svg as the
 * source of truth, and generate.
 *
 * The monogram viewBox is *measured*, not guessed — the glyph's bounding box
 * read out of a real browser with getBBox(), then padded. Run this after
 * replacing the .svg:
 *
 *   npm run brand:mark
 *
 * Needs Playwright, which is not a project dependency (it is only ever used by
 * one-off scripts like this one and the forced-password e2e check):
 *
 *   npm install --no-save playwright && npx playwright install chromium
 *
 * Set CHROMIUM_PATH to reuse a Chromium that is already on the machine instead
 * of downloading one.
 */
import fs from "node:fs";
import path from "node:path";

const SVG = "public/go-wordmark-navy.svg";
const OUT = "src/lib/brand-mark.ts";
const ICON_SVG = "src/app/icon.svg";
const APPLE_ICON = "src/app/apple-icon.png";
/** Space around the G in the favicon, as a fraction of the glyph's larger side. */
const MONOGRAM_PAD = 0.14;
/** Apple's home-screen icon size. */
const APPLE_ICON_PX = 180;
/** Brand navy — the same value the SVG fills with and Tailwind calls `navy`. */
const NAVY = "#1C1960";

function fail(message) {
  console.error(`brand-mark: ${message}`);
  process.exit(1);
}

if (!fs.existsSync(SVG)) fail(`${SVG} not found — run from the repo root.`);
const svg = fs.readFileSync(SVG, "utf8");

const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
if (!viewBoxMatch) fail("the SVG has no viewBox; add one before generating.");
const viewBox = viewBoxMatch[1];

const all = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
if (all.length === 0) fail("no <path> elements found.");

/**
 * Illustrator exports leave degenerate specks behind — this file carries a
 * 0.02-unit square at 307.49,142.08 as one path and three identical rects.
 * They paint nothing. Dropping anything with a near-zero bounding box keeps
 * them out without hard-coding this particular artefact's coordinates.
 */
let chromium;
try {
  ({ chromium } = await import("playwright"));
} catch {
  fail("playwright is not installed. Run: npm install --no-save playwright");
}

const browser = await chromium.launch(
  process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}
);
try {
  const page = await browser.newPage();
  await page.setContent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">` +
      all.map((d, i) => `<path id="p${i}" d="${d}"/>`).join("") +
      `</svg>`
  );
  const boxes = await page.evaluate(
    (n) =>
      Array.from({ length: n }, (_, i) => {
        const b = document.getElementById(`p${i}`).getBBox();
        return { x: b.x, y: b.y, width: b.width, height: b.height };
      }),
    all.length
  );

  const glyphs = all.filter((_, i) => boxes[i].width > 1 && boxes[i].height > 1);
  if (glyphs.length === 0) fail("every path measured as empty — is the SVG valid?");

  // The G is simply the leftmost glyph; it is the first letter of the wordmark.
  const kept = boxes.filter((b) => b.width > 1 && b.height > 1);
  let gIndex = 0;
  for (let i = 1; i < kept.length; i++) if (kept[i].x < kept[gIndex].x) gIndex = i;
  const g = kept[gIndex];

  // Square, and centred on the glyph. A favicon is drawn into a square box, so
  // a viewBox with the letter's own 1.03:1 ratio would letterbox it off-centre.
  const side = Math.max(g.width, g.height) * (1 + MONOGRAM_PAD * 2);
  const round = (n) => Math.round(n * 100) / 100;
  const monoX = round(g.x + g.width / 2 - side / 2);
  const monoY = round(g.y + g.height / 2 - side / 2);
  const monoSide = round(side);
  const monogramViewBox = [monoX, monoY, monoSide, monoSide].join(" ");

  const out = `// GENERATED by scripts/brand-mark.mjs from ${SVG} — do not edit by hand.
/**
 * The GoTutors mark, as path data.
 *
 * \`${SVG}\` stays the source of truth and is still the file served for
 * the favicon and anything outside React. The paths are mirrored here so the
 * mark can be drawn *inline*, which both consumers need and an \`<img>\` cannot
 * give them:
 *
 *  - On screen the sidebar and the login hero are navy, so the mark has to
 *    invert to white. An external SVG's own \`fill\` is not reachable from the
 *    page's CSS, and shipping a second white file means two files to keep in
 *    step. Inline, \`fill\` is an inherited property, so \`currentColor\` does it.
 *  - \`@react-pdf/renderer\` cannot load an SVG through \`<Image>\` — only PNG and
 *    JPEG. Its \`Svg\`/\`Path\` primitives take exactly these strings.
 *
 * To change the logo, replace the .svg and re-run \`npm run brand:mark\`.
 */

/** The full "GoTutors" wordmark, smile included. */
export const WORDMARK_VIEWBOX = "${viewBox}";

export const WORDMARK_PATHS: readonly string[] = [
${glyphs.map((d) => `  ${JSON.stringify(d)},`).join("\n")}
];

/**
 * The G alone, for square spaces the wordmark cannot fit — the favicon above
 * all, where a 3.4:1 wordmark would shrink to an illegible smear. The viewBox
 * is the glyph's measured bounding box padded evenly, so the letter sits
 * centred with room to breathe instead of bleeding off the edges.
 */
export const MONOGRAM_VIEWBOX = "${monogramViewBox}";

export const MONOGRAM_PATH = ${JSON.stringify(glyphs[gIndex])};
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);

  /**
   * The tab icon, from the same measurement. Next's App Router picks
   * `src/app/icon.svg` and `src/app/apple-icon.png` up by filename, so nothing
   * imports these — which is also why they are generated rather than drawn by
   * hand: there is no import to follow when someone wonders why the tab still
   * shows the old logo.
   */
  const iconSvg = `<!-- GENERATED by scripts/brand-mark.mjs — do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${monogramViewBox}">
  <rect x="${monoX}" y="${monoY}" width="${monoSide}" height="${monoSide}" rx="${round(side * 0.2)}" fill="${NAVY}"/>
  <path d="${glyphs[gIndex]}" fill="#ffffff"/>
</svg>
`;
  fs.writeFileSync(ICON_SVG, iconSvg);

  // iOS ignores SVG favicons, so the home-screen icon is rasterised here rather
  // than at request time — the browser is already open for the measurement.
  const shot = await browser.newPage({ viewport: { width: APPLE_ICON_PX, height: APPLE_ICON_PX } });
  await shot.setContent(
    `<style>html,body{margin:0;padding:0}svg{display:block}</style>` +
      iconSvg.replace("<svg ", `<svg width="${APPLE_ICON_PX}" height="${APPLE_ICON_PX}" `)
  );
  fs.writeFileSync(APPLE_ICON, await shot.screenshot({ omitBackground: true }));

  console.log(
    `brand-mark: wrote ${OUT} — ${glyphs.length} glyph paths (dropped ${all.length - glyphs.length} empty), ` +
      `monogram viewBox "${monogramViewBox}"\nbrand-mark: wrote ${ICON_SVG} and ${APPLE_ICON}`
  );
} finally {
  await browser.close();
}
